import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/Providers";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body
          className={`${roboto.className} h-screen w-screen overscroll-none`}
        >
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
